aws-samples/amazon-codeguru-reviewer-javascript-detectors

- test.txt
This is just a test PR from a regular GH account.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Create a test file

- .gitignore
- Test_PR.txt
- src/javascript/detectors/file_injection/file_injection.js
* Rules Added: javascript/file-injection@v1.0
> Add compliant and noncompliant examples of javascript/file-injection@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/insecure_connection/insecure_connection.js
* Rules Added: javascript/insecure-connection@v1.0
> Add compliant and noncompliant examples of javascript/insecure-connection@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/insecure_hashing/insecure_hashing.js
* Rules Added: javascript/insecure-hashing@v1.0
> Add compliant and noncompliant examples of javascript/insecure-hashing@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/cryptographic_key_generator/cryptographic_key_generator.js
* Rules Added: javascript/cryptographic-key-generator@v1.0
> Add compliant and noncompliant examples of javascript/cryptographic-key-generator@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/insecure_cryptography/insecure_cryptography.js
* Rules Added: javascript/insecure-cryptography@v1.0
> Add compliant and noncompliant examples of javascript/insecure-cryptography@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/header_injection/header_injection.js
* Rules Added: javascript/header-injection@v1.0
> Add compliant and noncompliant examples of javascript/header-injection@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/improper_restriction_of_frames/improper_restriction_of_frames.js
* Rules Added: javascript/improper-restriction-of-frames@v1.0
> Add compliant and noncompliant examples of javascript/improper-restriction-of-frames@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/insufficiently_protected_credentials/insufficiently_protected_credentials.js
* Rules Added: javascript/insufficiently-protected-credentials@v1.0
> Add compliant and noncompliant examples of javascript/insufficiently-protected-credentials@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/loose_file_permissions/loose_file_permissions.js
* Rules Added: javascript/loose-file-permissions@v1.0
> Add compliant and noncompliant examples of javascript/loose-file-permissions@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/stack_trace_exposure/stack_trace_exposure.js
* Rules Added: javascript/stack-trace-exposure@v1.0
> Add compliant and noncompliant examples of javascript/stack-trace-exposure@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/untrusted_deserialization/untrusted_deserialization.js
* Rules Added: javascript/untrusted-deserialization@v1.0
> Add compliant and noncompliant examples of javascript/untrusted-deserialization@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/weak_obfuscation_of_request/weak_obfuscation_of_request.js
* Rules Added: javascript/weak-obfuscation-of-request@v1.0
> Add compliant and noncompliant examples of javascript/weak-obfuscation-of-request@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/new_function_detected/new_function_detected.js
* Rules Added: javascript/new-function-detected@v1.0
> Add compliant and noncompliant examples of javascript/new-function-detected@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/xpath_injection/xpath_injection.js
* Rules Added: javascript/xpath-injection@v1.0
*  Added .gitignore
> Add compliant and noncompliant examples of javascript/xpath-injection@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/improper_input_validation/improper_input_validation.js
* Rules Added: javascript/improper-input-validation@v1.0
> Add compliant and noncompliant examples of javascript/improper-input-validation@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/sendfile_injection/sendfile_injection.js
* Rules Added: javascript/sendfile-injection@v1.0
> Add compliant and noncompliant examples of javascript/sendfile-injection@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/open_redirect/open_redirect.js
* Rules Added: javascript/open-redirect@v1.0
> Add compliant and noncompliant examples of javascript/open-redirect@v1.0

- .gitignore
- Test_PR.txt
- src/detectors/limit_on_request_content_length/limit_on_request_content_length.js
* Rules Added: limit-on-request-content-length@v1.0
> Add compliant and noncompliant examples of javascript/limit-on-request-content-length@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/server_side_request_forgery/server_side_request_forgery.js
* Rules Added: javascript/server-side-request-forgery@v1.0
> Add compliant and noncompliant examples of javascript/server-side-request-forgery@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/integer_overflow/integer_overflow.js
* Rules Added: javascript/integer-overflow@v1.0
> Add compliant and noncompliant examples of javascript/integer-overflow@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/dns_prefetching/dns_prefetching.js
* Rules Added: javascript/dns-prefetching@v1.0
> Add compliant and noncompliant examples of javascript/dns-prefetching@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/timing_attack/timing_attack.js
* Rules Added: javascript/timing-attack@v1.0
> Add compliant and noncompliant examples of javascript/timing-attack@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/least_privilege_violation/least_privilege_violation.js
* Rules Added: javascript/least-privilege-violation@v1.0
> Add compliant and noncompliant examples of javascript/least-privilege-violation@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/origins_verified_cross_origin_communication/origins_verified_cross_origin_communication.js
* Rules Added: javascript/origins-verified-cross-origin-communication@v1.0
> Add compliant and noncompliant examples of javascript/origins-verified-cross-origin-communication@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/logging_of_sensitive_information/logging_of_sensitive_information.js
* Rules Added: javascript/logging-of-sensitive-information@v1.0
> Add compliant and noncompliant examples of javascript/logging-of-sensitive-information@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/do_not_disable_html_autoescape/do_not_disable_html_autoescape.js
* Rules Added: javascript/do-not-disable-html-autoescape@v1.0
> Add compliant and noncompliant examples of javascript/do-not-disable-html-autoescape@v1.0

- .gitignore
- Test_PR.txt
- src/detectors/insecure_temporary_file/insecure_temporary_file.js
* Rules Added: insecure-temp-file@v1.0
> Add compliant and noncompliant examples of javascript/insecure-temp-file@v1.0

- .gitignore
- Test_PR.txt
- src/detectors/nosql_injection/nosql_injection.js
* Rules Added: nosql-injection@v1.0
> Add compliant and noncompliant examples of javascript/nosql-i njection@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/file_and_directory_information_exposure/file_and_directory_information_exposure.js
* Rules Added: javascript/file-and-directory-information-exposure@v1.0
> Add compliant and noncompliant examples of javascript/file-and-directory-information-exposure@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/session_fixation/session_fixation.js
* Rules Added: javascript/session-fixation@v1.0
> Add compliant and noncompliant examples of javascript/session-fixation@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/insecure_object_attribute_modification/insecure_object_attribute_modification.js
* Rules Added: javascript/insecure-object-attribute-modification@v1.0
> Add compliant and noncompliant examples of javascript/insecure-object-attribute-modification@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/non_literal_regular_expression/non_literal_regular_expression.js
* Rules Added: javascript/non-literal-regular-expression@v1.0
> Add compliant and noncompliant examples of javascript/non-literal-regular-expression@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/improper_access_control/improper_access_control.js
* Rules Added: javascript/improper-access-control@v1.0
> Add compliant and noncompliant examples of javascript/improper-access-control@v1.0

- .gitignore
- Test_PR.txt
- src/javascript/detectors/sql_injection/sql_injection.js
* Rules Added: javascript/sql-injection@v1.0
> Add compliant and noncompliant examples of javascript/sql-injection@v1.0

- src/javascript/detectors/insecure_cors_policy/insecure_cors_policy.js
Needs consistent spacing
*Issue #, if available:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Fix typo in defining Noncompliant description

- src/javascript/detectors/weak_obfuscation_of_request/weak_obfuscation_of_request.js
Fix typo
*Issue #, if available:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Fix typo in Compliant naming

- README.md
Not required
*Issue #, if available:*
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
> Revert change to README.md

- src/javascript/detectors/origins_verified_cross_origin_communications/origins_verified_cross_origin_communications.js
Rename communication to communications.
> Update and rename origins_verified_cross_origin_communication.js to origins_verified_cross_origin_communications.js

- README.md
*Issue #, if available:*
Modified the `README.md` file for JavaScript aws-samples.
> Modified the README.md file for JavaScript aws-samples
